sudo: required

services:
  - docker

env:
  DOCKER_COMPOSE_VERSION: 1.13.0

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

language: java

before_install:
  # update is required to update the repositories to see the new packages for
  # Docker.
  - sudo apt-get update

  # Now we can install the newer docker-engine which is required for the newer
  # docker-composer we will install next. The messy options are to force it to
  # be non-interactive (normally it asks you a bunch of config questions).
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine

  # Upgrade/install docker-compose.
  - sudo rm -f /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  # Print out the current docker-compose version.
  - docker-compose --version

script:
  - mvn clean install -Dhdp=2.4 | grep -v 'Download.* http://'
  - mvn verify -Dhdp=2.4 -Pdocker -f logisland-docker/pom.xml
  - docker-compose -f logisland-docker/src/it/resources/docker-compose.yml up
  - logisland-docker/src/it/resources/it.sh -d
  - docker-compose -f logisland-docker/src/it/resources/docker-compose.yml down
#  - mvn clean install -Dhdp=2.5

jdk:
  - oraclejdk8

install:
  - sudo sysctl -w vm.max_map_count=262144

notifications:
  email:
    - bailet.thomas@gmail.com

  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e305a73a60a02fefba40
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always




