# use Docker-based container (instead of OpenVZ)
sudo: false

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

language: java

script: 
  - mvn install -Phdp-2.4
  - mvn install -Phdp-2.5

jdk:
  - oraclejdk8

install: true

notifications:
  email:
    - bailet.thomas@gmail.com

  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e305a73a60a02fefba40
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always




