# use Docker-based container (instead of OpenVZ)
sudo: false

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

language: java

script: 
  - mvn package -DskipTests

jdk:
  - oraclejdk8
  - openjdk8

notifications:
  email:
    - bailet.thomas@gmail.com

