# use Docker-based container (instead of OpenVZ)
sudo: false

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

language: java

before_install:
  # Print out the current docker-compose version.
  - docker-compose --version

script:
  - mvn clean install -Dhdp=2.4
  - mvn verify -Dhdp=2.4 -Pdocker -f logisland-docker/pom.xml
  - docker-compose -f logisland-docker/src/it/resources/docker-compose.yml up
  - logisland-docker/src/it/resources/it.sh -d
  - docker-compose -f logisland-docker/src/it/resources/docker-compose.yml down
#  - mvn clean install -Dhdp=2.5

jdk:
  - oraclejdk8

install:
  - sudo sysctl -w vm.max_map_count=262144

notifications:
  email:
    - bailet.thomas@gmail.com

  webhooks:
    urls:
      - https://webhooks.gitter.im/e/e305a73a60a02fefba40
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always




