# Docker compose fil for setting up a logisland monitoring stack
version: '3.2'

services:

  # We first need a Prometheus DB running to store all our metrics
  prometheus:
    image: 'prom/prometheus:latest'
    command: '-config.file=/etc/prometheus/conf/prometheus.yml -storage.local.path=/prometheus -web.console.libraries=/usr/share/prometheus/console_libraries -web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - itnet
    ports:
      - '9090:9090'
    volumes:
      - './prometheus/conf:/etc/prometheus/conf'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  # we also need Grafan to plot these metric
  grafana:
    image: 'grafana/grafana:latest'
    networks:
      - itnet
    ports:
      - '3000:3000'
    restart: always
    depends_on:
      - prometheus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  elasticsearch-exporter:
    image: 'justwatch/elasticsearch_exporter:1.0.1'
    command:
      - '-es.uri=http://${ES_HOST}:${ES_PORT}'
      - '-es.all=true'
    networks:
      - itnet
    ports:
      - '9108:9108'

  burrow:
    command: /go/bin/burrow --config /etc/burrow/conf/burrow.cfg
    image: 'hurence/burrow:latest'
    #links:
     # - 'kafka.logisland:kafka'
     # - 'zookeeper.logisland:zookeeper'
    networks:
      - itnet
    ports:
      - '7074:7074'
    volumes:
      - './burrow:/etc/burrow'

  burrow-exporter:
    entrypoint: 'go-wrapper run --metrics-addr 192.168.1.21:7075 --interval 10 --burrow-addr http://192.168.1.21:7074'
    image: 'hurence/burrow-exporter:latest'
    networks:
      - itnet
    ports:
      - '7075:7075'

networks:
  itnet: