swagger: '2.0'
info:
  description: REST API for logisland agent
  version: v1
  title: logisland-agent
  contact:
    name: Thomas Bailet
    email: bailet.thomas@gmail.com
host: localhost:8081
basePath: /
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:

  /:
    get:
      summary: the root resource
      description: / entrypoint
      responses:
        200:
          description: OK

  /processors:
    get:
      tags:
       - config
      operationId: getProcessors
      summary:  get all processors
      description: get all processors
      responses:
        "200":
          description: processors
          schema:
            type: string
        default:
          description: unexpected error
          schema:
            $ref: 'error.yml'

  # Job API
  /configs:
    get:
      tags:
       - config
      operationId: getConfig
      summary:  global config
      description: get all global configuration properties
      responses:
        "200":
          description: global configuration
          schema:
            type: array
            items:
              $ref: 'property.yml'
        default:
          description: unexpected error
          schema:
            $ref: 'error.yml'

  # Job API
  /jobs:
    get:
      tags:
       - job
      operationId: getAllJobs
      summary:  get all jobs
      description: retrieve all jobs (retrieve only summary fields)
      responses:
        "200":
          description: job configuration list
          schema:
            type: array
            items:
              $ref: 'job.yml'
        default:
          description: unexpected error
          schema:
            $ref: 'error.yml'
    post:
      tags:
       - job
      summary:  create new job
      description:  store a new job configuration if valid
      operationId: addJob
      parameters:
        - name: job
          in: body
          description: Job to add to the store
          required: true
          schema:
            $ref: 'job.yml'
      responses:
        "404":
          description: Job not found
        "400":
          description: Invalid ID supplied
        "200":
          description: Job successfuly created
          schema:
            $ref: 'job.yml'
        default:
          description: unexpected error
          schema:
            $ref: 'error.yml'

  /jobs/metrics:
     get:
      tags:
        - job
      summary: get job metrics
      description: get the metrics of corresponding Job
      operationId: getJobMetrics
      parameters:
        - name: count
          in: query
          description: max number of ites to retrieve
          required: false
          type: integer
          default: 20
      responses:
        "200":
          description: job metrics
          schema:
            type: array
            items:
              $ref: 'metrics.yml'
        default:
          description: unexpected error
          schema:
            $ref: 'error.yml'

  /jobs/alerts:
     get:
      tags:
        - job
      summary: get job alerts
      description: get the alerts
      operationId: getJobAlerts
      parameters:
        - name: count
          in: query
          description: max number of ites to retrieve
          required: false
          type: integer
          default: 20
      responses:
        "200":
          description: job metrics
          schema:
            type: array
            items:
              $ref: 'metrics.yml'
        default:
          description: unexpected error
          schema:
            $ref: 'error.yml'

  /jobs/errors:
     get:
      tags:
        - job
      summary: get last job errors
      description: get the errors
      operationId: getJobErrors
      parameters:
        - name: count
          in: query
          description: max number of ites to retrieve
          required: false
          type: integer
          default: 20
      responses:
        "200":
          description: job errors
          schema:
            $ref: 'job.yml'
        default:
          description: unexpected error
          schema:
            $ref: 'error.yml'


  /jobs/{jobId}:
    get:
      tags:
        - job
      summary: get job
      description: get the corresponding Job definition
      operationId: getJob
      produces:
        - application/json
        - text/plain
      parameters:
        - name: jobId
          in: path
          description: id of the job to return
          required: true
          type: string
      responses:
        "200":
          description: job definition
          schema:
            $ref: 'job.yml'
        default:
          description: unexpected error
          schema:
            $ref: 'error.yml'
    delete:
      tags:
        - job
      summary: delete job
      description: remove the corresponding Job definition and stop if its currently running
      operationId: deleteJob
      parameters:
        - name: jobId
          in: path
          description: id of the job to return
          required: true
          type: string
      responses:
        "404":
          description: Job not found
        "400":
          description: Invalid ID supplied
        "200":
          description: job successfully removed
          schema:
            $ref: 'job.yml'
        default:
          description: unexpected error
          schema:
            $ref: 'error.yml'
    put:
      tags:
       - job
      summary:  update job
      description: update an existing job configuration if valid
      operationId: updateJob
      parameters:
        - name: jobId
          in: path
          description: Job to add to the store
          required: true
          type: string
        - name: job
          in: body
          description: Job to add to the store
          required: true
          schema:
            $ref: 'job.yml'
      responses:
        "200":
          description: Job successfuly created
          schema:
            $ref: 'job.yml'
    post:
      tags:
       - job
      summary:  create new job
      description:  store a new job configuration if valid
      operationId: addJobWithId
      parameters:
        - name: body
          in: body
          description: Job configuration to add to the store
          required: true
          schema:
            $ref: 'job.yml'
        - name: jobId
          in: path
          description: JobId to add to the store
          required: true
          type: string
      responses:
        "404":
          description: Job not found
        "400":
          description: Invalid ID supplied
        "200":
          description: Job successfuly created
          schema:
            $ref: 'job.yml'
        default:
          description: unexpected error
          schema:
            $ref: 'error.yml'
  /jobs/{jobId}/restart:
     post:
      tags:
        - job
      summary: start job
      description: start the corresponding Job definition
      operationId: reStartJob
      parameters:
        - name: jobId
          in: path
          description: id of the job to restart
          required: true
          type: string
      responses:
        "200":
          description: job successfuly started
          schema:
            $ref: 'job.yml'
        default:
          description: unexpected error
          schema:
            $ref: 'error.yml'
  /jobs/{jobId}/start:
     post:
      tags:
        - job
      summary: start job
      description: start the corresponding Job definition
      operationId: startJob
      parameters:
        - name: jobId
          in: path
          description: id of the job to return
          required: true
          type: string
      responses:
        "200":
          description: job successfuly started
          schema:
            $ref: 'job.yml'
        default:
          description: unexpected error
          schema:
            $ref: 'error.yml'
  /jobs/{jobId}/shutdown:
     post:
      tags:
        - job
      summary: shutdown job
      description: shutdown the running Job
      operationId: shutdownJob
      parameters:
        - name: jobId
          in: path
          description: id of the job to return
          required: true
          type: string
      responses:
        "200":
          description: job successfuly started
          schema:
            $ref: 'job.yml'
        default:
          description: unexpected error
          schema:
            $ref: 'error.yml'
  /jobs/{jobId}/pause:
     post:
      tags:
        - job
      summary: pause job
      description: pause the corresponding Job
      operationId: pauseJob
      parameters:
        - name: jobId
          in: path
          description: id of the job to return
          required: true
          type: string
      responses:
        "200":
          description: job successfuly paused
          schema:
            $ref: 'job.yml'
        default:
          description: unexpected error
          schema:
            $ref: 'error.yml'
  /jobs/{jobId}/status:
     get:
      tags:
        - job
      summary: get job status
      description: get the status of corresponding Job
      operationId: getJobStatus
      parameters:
        - name: jobId
          in: path
          description: id of the job to return
          required: true
          type: string
      responses:
        "200":
          description: job status
          schema:
            type: string
        default:
          description: unexpected error
          schema:
            $ref: 'error.yml'
  /jobs/{jobId}/version:
     get:
      tags:
        - job
      summary: get job version
      description: get the version of corresponding Job
      operationId: getJobVersion
      parameters:
        - name: jobId
          in: path
          description: id of the job to return
          required: true
          type: string
      responses:
        "200":
          description: job version
          schema:
            type: string
        default:
          description: unexpected error
          schema:
            $ref: 'error.yml'
  /jobs/{jobId}/engine:
     get:
      tags:
        - job
        - engine
      summary: get job engine configuration
      description: this is usefull when you want to launch a spark app within YARN to retrieve the launching config before submitting the job itself
      produces:
        - text/plain
      operationId: getJobEngine
      parameters:
        - name: jobId
          in: path
          description: id of the job to return
          required: true
          type: string
      responses:
        "200":
          description: job status
          schema:
            type: string
        default:
          description: unexpected error
          schema:
            $ref: 'error.yml'

  # Topics API
  /topics:
    get:
      tags:
        - topic
      summary: get all topics
      operationId: getAllTopics
      parameters: []
      responses:
        '200':
          description: Status 200
          schema:
            type: array
            items:
              $ref: 'topic.yml'
    post:
      tags:
          - topic
      summary: create new topic
      operationId: addNewTopic
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: 'topic.yml'
      responses:
        '200':
          description: Status 200
  /topics/{topicId}:
    get:
      tags:
        - topic
      summary: get topic
      operationId: getTopic
      parameters:
        - name: topicId
          in: path
          required: true
          type: string
      responses:
        "200":
          description: Status 200
          schema:
            $ref: 'topic.yml'
        default:
          description: unexpected error
          schema:
            $ref: 'error.yml'
    put:
      tags:
          - topic
      summary: update topic
      operationId: updateTopic
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: 'topic.yml'
        - name: topicId
          in: path
          required: true
          type: string
      responses:
        "200":
          description: job successfuly started
          schema:
            $ref: 'topic.yml'
        default:
          description: unexpected error
          schema:
            $ref: 'error.yml'
    delete:
      tags:
        - topic
      summary: delete topic
      description: remove a topic config and remove all content from Kafka
      operationId: deleteTopic
      parameters:
        - name: topicId
          in: path
          required: true
          type: string
      responses:
        "200":
          description: topic successfully deleted
          schema:
            type: string
        default:
          description: unexpected error
          schema:
            $ref: 'error.yml'
  /topics/{topicId}/keySchema:
    get:
      tags:
        - schema
      summary: get topic key schema
      operationId: getTopicKeySchema
      parameters:
        - name: topicId
          in: path
          required: true
          type: string
        - name: version
          in: query
          description: version of the schema ("latest" if not provided)
          required: false
          type: string
          default: latest
      responses:
        "200":
          description: Avro schema
          schema:
            type: string
        default:
          description: unexpected error
          schema:
            $ref: 'error.yml'
    put:
      tags:
        - schema
      summary: update topic key schema
      operationId: updateTopicKeySchema
      parameters:
        - name: body
          in: body
          description: schema to add to the store
          required: true
          schema:
            type: string
        - name: topicId
          in: path
          description: id of the job to return
          required: true
          type: string
      responses:
        "200":
          description: Avro schema
          schema:
            type: string
        default:
          description: unexpected error
          schema:
            $ref: 'error.yml'
  /topics/{topicId}/keySchema/checkCompatibility:
    post:
      tags:
        - schema
      summary: check topic key schema compatibility
      operationId: checkTopicKeySchemaCompatibility
      parameters:
        - name: body
          in: body
          description: Avro schema as a json string
          required: true
          schema:
            type: string
        - name: topicId
          in: path
          description: id of the job to return
          required: true
          type: string
      responses:
        "200":
          description: compatibility level
          schema:
            type: string
        default:
          description: unexpected error
          schema:
            $ref: 'error.yml'
  /topics/{topicId}/valueSchema:
    get:
      tags:
        - schema
      summary: get topic value schema
      operationId: getTopicValueSchema
      parameters:
        - name: topicId
          in: path
          description: id of the job to return
          required: true
          type: string
        - name: version
          in: query
          description: version of the schema ("latest" if not provided)
          required: false
          type: string
          default: latest
      responses:
        "200":
          description: job definition
          schema:
            type: string
        default:
          description: unexpected error
          schema:
            $ref: 'error.yml'
    put:
      tags:
        - schema
      summary: update topic value schema
      operationId: updateTopicValueSchema
      parameters:
        - name: body
          in: body
          description: Avro schema as a json string
          required: true
          schema:
            type: string
        - name: topicId
          in: path
          description: id of the job to return
          required: true
          type: string

      responses:
        "200":
          description: Avro schema
          schema:
            type: string
        default:
          description: unexpected error
          schema:
            $ref: 'error.yml'
  /topics/{topicId}/valueSchema/checkCompatibility:
    post:
      tags:
        - schema
      summary: check topic value schema compatibility
      operationId: checkTopicValueSchemaCompatibility
      parameters:
        - name: topicId
          in: path
          description: id of the job to return
          required: true
          type: string
        - name: body
          in: body
          description: Avro schema as a json string
          required: true
          schema:
            type: string
      responses:
        "200":
          description: compatibility level
          schema:
            type: string
        default:
          description: unexpected error
          schema:
            $ref: 'error.yml'





















