version: 0.1
documentation: LogIsland analytics main config file. Put here every engine or component config

components:
  # Main event streaming engine
  - component: com.hurence.logisland.engine.EventProcessorJob
    type: engine
    version: 0.1.0
    documentation: Main Logisland job entry point
    configuration:
      spark.master: local[8]
      spark.executorMemory: 4g
      spark.checkpointingDirectory: file:///tmp
      spark.appName: My first stream component
      spark.streaming.batchDuration: 2000
      spark.serializer: org.apache.spark.serializer.KryoSerializer
      spark.streaming.backpressure.enabled: true
      spark.streaming.unpersist: false
      spark.streaming.blockInterval: 350
      spark.streaming.kafka.maxRatePerPartition:
      spark.ui.port: 4050
      kafka.metadata.broker.list: sandbox:2181

  # Match Lucene queries
  - component: com.hurence.logisland.component.QueryMatcherProcessor
    type: component
    version: 1.0
    documentation:
    configuration:
      inputTopic: kafka_log
      outputTopic: kafka_event
      rules:
        - name: rule 1
          query: incident*
        - name: rule 2
          query: vehicule*

  # Detect outliers
  - component: com.hurence.logisland.component.OutlierProcessor
    type: component
    version: 1.0
    documentation:
    configuration:
      inputTopic: kafka_log
      outputTopic: kafka_event
      rotationPolicy:
        type: BY_AMOUNT
        amount : 100
        unit: POINTS
      chunkingPolicy:
        type: BY_AMOUNT
        amount: 10
        unit: POINTS
      globalStatistics :
      sketchyOutlierAlgorithm: SKETCHY_MOVING_MAD
      batchOutlierAlgorithm:
        type: RAD
        config:
          minAmountToPredict: 100
          reservoirSize: 100
          minZscorePercentile: 95
          zscoreCutoffs:
            NORMAL: 0.000000000000001
            MODERATE_OUTLIER: 1.5